INSERT INTO category(NAME, REG_DATE) VALUES('spring', CURRENT_TIMESTAMP());
INSERT INTO category(NAME, REG_DATE) VALUES('java', CURRENT_TIMESTAMP());

INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES('테스트', '지금 포스팅은 테스트 포스팅 입니다.', '지금 포스팅은 테스트 포스팅 입니다.', 'Y', CURRENT_TIMESTAMP(), 1);